services:
  app:
    build: .
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    env_file:
      - .env
    volumes:
      - ./data:/app/data 
    restart: always
    command: ["sh", "-c", "uvicorn app.main:app --host ${HOST:-0.0.0.0} --port ${PORT:-8080}"]

  tests:
    build: .
    env_file:
      - .env
    volumes:
      - ./data:/app/data 
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    command: ["sh", "-c", "pytest"]