services:
  app:
    build: .
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs 
    restart: always
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

volumes:
  mongo_data: