services:
  app:
    build: .
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    env_file:
      - .env
    volumes:
      - ./data:/app/data 
      - ./logs:/app/logs 
    restart: always

  tests:
    build: .
    env_file:
      - .env
    volumes:
      - ./data:/app/data 
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    command: ["sh", "-c", "pytest"]